### ISSUE TITLE
Gives invalid options for setting the weight of an entry

### ISSUE THREAD

**Issue by HalbFettKaese** [misode/loot-table#24]
Minecraft only supports setting the weight of an entry to an exact value, so when attempting to fill in a range or a binomial distribution, the resulting loot table causes the error `Expected weight to be a Int, was an object` in the game output log and makes the entire loot table invalid.

However, the loot table generator does give the option of setting the weight to a range or a binomial distribution. To prevent the generation of invalid loot tables, this option should be removed.

The versions I tested this in were Minecraft 1.14.4 and Minecraft 1.15 Pre-release 7.

**Comment by SPGoding** [comment]
Also affects `quality` I guess.

**Comment by misode** [comment]
Thanks for the fix @SPGoding!
